openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Users 
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /api/users:
    get:
      summary: List all tanks
      operationId: listTanks
      tags:
        - tanks
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of tanks
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Tanks"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a tank
      operationId: createTanks
      tags:
        - tanks
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tanks/{tankId}:
    get:
      summary: Info for a specific tank
      operationId: showTankById
      tags:
        - tanks
      parameters:
        - name: tankId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tank"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Tank:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Tanks:
      type: array
      items:
        $ref: "#/components/schemas/Tank"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
